Repository Dev-FE-2/toy-project1-team2-intranet-project, pull requests merged in 2024-10, with the labels that each got.

#5 [CHORE] PR 시 auto assignee를 추가합니다.
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: 🔧 CHORE, 🔍 TEST

#13 [feat] 공통 레이아웃 header,nav
  README.md
  css/index.css
  css/signup.css
  html/main.html
  html/signup.html
  index.html
  public/fonts/wotf/Pretendard-Black.woff
  public/fonts/wotf/Pretendard-Bold.woff
  public/fonts/wotf/Pretendard-ExtraBold.woff
  public/fonts/wotf/Pretendard-ExtraLight.woff
  public/fonts/wotf/Pretendard-Light.woff
  public/fonts/wotf/Pretendard-Medium.woff
  public/fonts/wotf/Pretendard-Regular.woff
  public/fonts/wotf/Pretendard-SemiBold.woff
  public/fonts/wotf/Pretendard-Thin.woff
  public/fonts/wotf2/Pretendard-Black.woff2
  public/fonts/wotf2/Pretendard-Bold.woff2
  public/fonts/wotf2/Pretendard-ExtraBold.woff2
  public/fonts/wotf2/Pretendard-ExtraLight.woff2
  public/fonts/wotf2/Pretendard-Light.woff2
  public/fonts/wotf2/Pretendard-Medium.woff2
  public/fonts/wotf2/Pretendard-Regular.woff2
  public/fonts/wotf2/Pretendard-SemiBold.woff2
  public/fonts/wotf2/Pretendard-Thin.woff2
  public/vite.svg
  src/App.js
  src/Container.js
  src/components/headers/Header.css
  src/components/headers/Header.js
  src/components/layouts/Layout.js
  src/components/nav-bars/Navbar.css
  src/components/nav-bars/Navbar.js
  src/counter.js
  src/javascript.svg
  src/main.js
  src/pages/admin/home/Home.js
  src/pages/admin/member/Member.js
  src/pages/admin/notice/Notice.js
  src/pages/admin/vacation-management/VacationManagement.js
  src/pages/membes/Member.js
  src/pages/not-found/NotFound.js
  src/pages/user/course/Course.js
  src/pages/user/edit-profile/EditProfile.css
  src/pages/user/edit-profile/EditProfile.js
  src/pages/user/home/Home.js
  src/pages/user/notice/Notice.js
  src/pages/user/peer/Peer.js
  src/pages/user/vacation-management/VacationManagement.js
  src/pages/user/work-detail/WorkDetail.js
  src/reset.css
  src/routes/Router.js
  src/style.css
  src/utils/constants.js
  src/utils/storage.js
Labels: 🚀 FEAT

#20 [FEAT] 로그인폼을 구현합니다.
  src/assets/auth/login_page.png
  src/components/common/log-in-form/LogInForm.css
  src/components/common/log-in-form/LogInForm.js
  src/components/common/sign-in-form/SignInForm.css
  src/components/common/sign-in-form/SignInForm.js
  src/pages/index.js
  src/pages/log-in/LogIn.css
  src/pages/log-in/LogIn.js
  src/pages/sign-in/SignIn.css
  src/pages/sign-in/SignIn.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#22 [Design] global.css 수정, 레이아웃 반응형 추가
  server/data/absences.json
  server/data/company_posts.json
  server/data/time_punch.json
  server/data/users.json
  src/App.js
  src/assets/imgs/logo/logo.png
  src/assets/imgs/profile/profile_null.jpg
  src/components/common/header/Header.css
  src/components/common/header/Header.js
  src/components/common/navbar/Navbar.css
  src/components/common/navbar/Navbar.js
  src/layout/Layout.css
  src/layout/Layout.js
  src/pages/index.js
  src/pages/not-found/NotFound.css
  src/pages/not-found/NotFound.js
  src/pages/user/edit-profile/EditProfile.css
  src/pages/user/notice/Notice.js
  src/routes/Router.js
  src/styles/global.css
  src/styles/reset.css
  src/utils/responsive.js
  src/utils/storage.js
Labels: 🚀 FEAT, 🌴 STYLE, 💻 FE

#26 [Style] 버튼 css 템플릿 생성
  src/components/common/header/Header.js
  src/pages/not-found/NotFound.js
  src/styles/global.css
Labels: 🌴 STYLE, 💻 FE

#29 feat: 직원 목록 불러오기
  src/apis/ApiClient.js
  src/components/ui/button/Button.css
  src/components/ui/button/Button.js
  src/pages/admin/member/member-management/MemberManagement.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/styles/global.css
Labels: 🚀 FEAT, 💻 FE

#21 feat(profile): edit-profile 구현
  package-lock.json
  package.json
  server/data/users.json
  src/components/ui/form/FormValidation.js
  src/components/user/form/edit-profile-form/EditProfileForm.css
  src/components/user/form/edit-profile-form/EditProfileForm.js
  src/components/user/profile/ProfileImage.css
  src/components/user/profile/ProfileImage.js
  src/pages/user/edit-profile/EditProfile.css
  src/pages/user/edit-profile/EditProfile.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#28 [Feat] user notice 작업
  package-lock.json
  package.json
  public/assets/fonts/wotf/Pretendard-Black.woff
  public/assets/fonts/wotf/Pretendard-Bold.woff
  public/assets/fonts/wotf/Pretendard-ExtraBold.woff
  public/assets/fonts/wotf/Pretendard-ExtraLight.woff
  public/assets/fonts/wotf/Pretendard-Light.woff
  public/assets/fonts/wotf/Pretendard-Medium.woff
  public/assets/fonts/wotf/Pretendard-Regular.woff
  public/assets/fonts/wotf/Pretendard-SemiBold.woff
  public/assets/fonts/wotf/Pretendard-Thin.woff
  public/assets/fonts/wotf2/Pretendard-Black.woff2
  public/assets/fonts/wotf2/Pretendard-Bold.woff2
  public/assets/fonts/wotf2/Pretendard-ExtraBold.woff2
  public/assets/fonts/wotf2/Pretendard-ExtraLight.woff2
  public/assets/fonts/wotf2/Pretendard-Light.woff2
  public/assets/fonts/wotf2/Pretendard-Medium.woff2
  public/assets/fonts/wotf2/Pretendard-Regular.woff2
  public/assets/fonts/wotf2/Pretendard-SemiBold.woff2
  public/assets/fonts/wotf2/Pretendard-Thin.woff2
  public/assets/imgs/auth/login_page.png
  public/assets/imgs/logo/logo.png
  public/assets/imgs/post/post1.jpg
  public/assets/imgs/post/post2.jpg
  public/assets/imgs/post/post3.jpg
  public/assets/imgs/post/post4.jpg
  public/assets/imgs/profile/profile_null.jpg
  server/data/company_posts.json
  server/data/users.json
  src/components/common/header/Header.css
  src/components/common/header/Header.js
  src/components/common/log-in-form/LogInForm.js
  src/components/common/navbar/Navbar.css
  src/components/common/notice/Notice.css
  src/components/common/notice/Notice.js
  src/components/index.js
  src/components/ui/button/Button.css
  src/pages/index.js
  src/pages/log-in/LogIn.js
  src/pages/user/notice/Notice.css
  src/pages/user/notice/Notice.js
  src/routes/Router.js
  src/styles/global.css
  src/utils/storage.js
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#36 [FEAT] 관리자 메인 페이지에 공지 게시판을 퍼블리싱합니다.
  src/components/admin/home/notice/Notice.css
  src/components/admin/home/notice/Notice.js
  src/components/admin/home/notice/NoticeHeader.css
  src/components/admin/home/notice/NoticeHeader.js
  src/components/admin/home/notice/NoticeItem.css
  src/components/admin/home/notice/NoticeItem.js
  src/components/admin/home/user-list/UserList.css
  src/components/admin/home/user-list/UserList.js
  src/components/admin/home/user-list/UserListHeader.css
  src/components/admin/home/user-list/UserListHeader.js
  src/pages/admin/home/Home.css
  src/pages/admin/home/Home.js
Labels: 🚀 FEAT, 💻 FE

#35 [Feat] 유저 공지 상세 페이지 제작
  src/components/admin/home/user-list/UserListHeader.js
  src/components/common/header/Header.js
  src/components/common/log-in-form/LogInForm.js
  src/components/common/notice/Notice.css
  src/components/common/notice/Notice.js
  src/components/index.js
  src/components/ui/button/Button.css
  src/components/ui/button/Button.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/index.js
  src/pages/not-found/NotFound.js
  src/pages/user/notice/Notice.css
  src/pages/user/notice/Notice.js
  src/pages/user/notice/notice-detail/NoticeDetail.css
  src/pages/user/notice/notice-detail/NoticeDetail.js
  src/pages/user/notice/notice-list/NoticeList.css
  src/pages/user/notice/notice-list/NoticeList.js
  src/routes/Router.js
  src/styles/global.css
  src/utils/constants.js
  src/utils/extractParams.js
  src/utils/navigation.js
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#39 [STYLE] 버튼 컴포넌트를 일부 수정합니다.
  src/components/admin/home/notice/NoticeHeader.css
  src/components/admin/home/notice/NoticeHeader.js
  src/components/admin/home/user-list/UserList.css
  src/components/admin/home/user-list/UserList.js
  src/components/admin/home/user-list/UserListHeader.css
  src/components/admin/home/user-list/UserListHeader.js
  src/components/common/header/Header.js
  src/components/ui/button/Button.js
  src/pages/admin/member/member-management/MemberManagement.js
Labels: 🔨 REFACTOR, 🌴 STYLE, 💻 FE

#42 [feat] : admin member pagination 기능 추가
  src/components/common/pagenation/Pagenation.css
  src/components/common/pagenation/Pagenation.js
  src/components/ui/button/Button.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/styles/global.css
Labels: 🚀 FEAT, 💻 FE

#43 [FEAT] 수강생 목록 홈페이지
  src/components/user/peer-list/PeerList.css
  src/components/user/peer-list/PeerList.js
  src/pages/user/peer/Peer.css
  src/pages/user/peer/Peer.js
Labels: 🚀 FEAT, 💻 FE

#50 [feat] : 관리자 직원 목록 검색 기능 구현
  src/components/common/pagenation/Pagenation.js
  src/pages/admin/member/member-management/MemberManagement.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/user/peer/Peer.js
Labels: 🚀 FEAT, 💻 FE

#52 [FEAT] 관리자 휴가/공가 관리 페이지를 퍼블리싱합니다.
  server/data/absences.json
  src/components/admin/vacation-management/VacationHeader.css
  src/components/admin/vacation-management/VacationHeader.js
  src/components/admin/vacation-management/VacationList.css
  src/components/admin/vacation-management/VacationList.js
  src/components/ui/accordion/Accordion.css
  src/components/ui/accordion/Accordion.js
  src/pages/admin/vacation-management/VacationManagement.css
  src/pages/admin/vacation-management/VacationManagement.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#51 [FEAT] 사용자 출근/퇴근 관리 페이지 구현
  server/data/time_punch.json
  src/components/user/peer-list/PeerList.css
  src/components/user/work-info/WorkInfo.css
  src/components/user/work-info/WorkInfo.js
  src/pages/user/peer/Peer.js
  src/pages/user/work-detail/WorkDetail.css
  src/pages/user/work-detail/WorkDetail.js
  src/routes/Router.js
  src/utils/generateCalendar.js
Labels: 🚀 FEAT, 💻 FE

#46 [Feat] 사용자 휴가/공가 폼
  public/assets/imgs/profile/profile2.jpg
  server/data/users.json
  src/components/admin/home/notice/NoticeItem.css
  src/components/admin/home/user-list/UserList.css
  src/components/common/header/Header.css
  src/components/common/header/Header.js
  src/components/index.js
  src/components/ui/button/Button.js
  src/components/ui/form/FormValidation.js
  src/components/user/form/edit-profile-form/EditProfileForm.css
  src/components/user/form/edit-profile-form/EditProfileForm.js
  src/components/user/form/vacation-form/VacationForm.js
  src/components/user/form/vacation-request-form/VacationRequestForm.css
  src/components/user/form/vacation-request-form/VacationRequestForm.js
  src/components/user/peer-list/PeerList.css
  src/components/user/profile/ProfileImage.css
  src/components/user/profile/ProfileImage.js
  src/layout/Layout.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/index.js
  src/pages/log-in/LogIn.css
  src/pages/user/edit-profile/EditProfile.css
  src/pages/user/edit-profile/EditProfile.js
  src/pages/user/notice/notice-list/NoticeList.css
  src/pages/user/notice/notice-list/NoticeList.js
  src/pages/user/peer/Peer.js
  src/pages/user/vacation/upload-vacation/UploadVacation.css
  src/pages/user/vacation/upload-vacation/UploadVacation.js
  src/pages/user/vacation/vacation-request/VacationRequest.css
  src/pages/user/vacation/vacation-request/VacationRequest.js
  src/routes/Router.js
  src/styles/global.css
  src/utils/constants.js
  src/utils/handleProfileImg.js
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#58 [FEAT] 관리자 휴가/공가 관리 페이지에서 셀렉트에 따른 필터링을 합니다.
  src/components/admin/vacation-management/VacationHeader.js
  src/components/admin/vacation-management/VacationList.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/utils/sortByName.js
Labels: 🚀 FEAT, 💻 FE

#60 [FEAT] 관리자 - 공지 관리 페이지를 퍼블리싱합니다.
  src/components/admin/home/notice/Notice.js
  src/components/admin/home/notice/NoticeItem.js
  src/components/admin/notice-management/NoticeManagementHeader.css
  src/components/admin/notice-management/NoticeManagementHeader.js
  src/components/admin/notice-management/NoticeManagementItem.css
  src/components/admin/notice-management/NoticeManagementItem.js
  src/components/admin/notice-management/NoticeManagementList.css
  src/components/admin/notice-management/NoticeManagementList.js
  src/components/common/notice/AdminNoticeItem.js
  src/components/common/notice/AdminNoticeList.js
  src/pages/admin/notice/notice-management/NoticeManagement.css
  src/pages/admin/notice/notice-management/NoticeManagement.js
  src/pages/admin/vacation-management/VacationManagement.css
  src/pages/admin/vacation-management/VacationManagement.js
  src/routes/Router.js
  src/utils/constants.js
Labels: 🚀 FEAT, 💻 FE

#55 [Feat] 사용자 휴가/공가 페이지
  server/data/absences.json
  server/data/time_punch.json
  server/data/users.json
  src/components/admin/home/notice/Notice.js
  src/components/admin/home/notice/NoticeItem.css
  src/components/admin/vacation-management/VacationList.js
  src/components/common/header/Header.css
  src/components/common/header/Header.js
  src/components/common/notice/Notice.css
  src/components/common/notice/Notice.js
  src/components/common/notice/NoticeItem.css
  src/components/common/notice/NoticeItem.js
  src/components/index.js
  src/components/user/form/vacation-request-form/VacationRequestForm.js
  src/components/user/vacation/vacation-header/VacationHeader.css
  src/components/user/vacation/vacation-header/VacationHeader.js
  src/components/user/vacation/vacation-list/VacationList.css
  src/components/user/vacation/vacation-list/VacationList.js
  src/components/user/vacation/vacation-table/VacationTable.css
  src/components/user/vacation/vacation-table/VacationTable.js
  src/layout/Layout.css
  src/pages/admin/home/Home.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/admin/vacation-management/VacationManagement.js
  src/pages/user/home/Home.js
  src/pages/user/notice/notice-list/NoticeList.css
  src/pages/user/notice/notice-list/NoticeList.js
  src/pages/user/vacation/vacation-management/VacationManagement.css
  src/pages/user/vacation/vacation-management/VacationManagement.js
  src/pages/user/vacation/vacation-request/VacationRequest.js
  src/routes/Router.js
  src/styles/global.css
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#63 [feat] 직원 목록 상세보기
  src/components/index.js
  src/pages/admin/member/member-detail/MemberDetail.css
  src/pages/admin/member/member-detail/MemberDetail.js
  src/pages/admin/member/member-detail/MemberDetail.js.css
  src/pages/admin/member/member-detail/MemberDetail.js.js
  src/pages/admin/member/member-management/MemberManagement.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/index.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#64 [feat] 관리자 직원 업로드 기능
  src/components/common/pagenation/Pagenation.js
  src/components/user/profile/ProfileImage.js
  src/pages/admin/member/member-detail/MemberDetail.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/admin/member/upload-member/UploadMember.css
  src/pages/admin/member/upload-member/UploadMember.js
  src/pages/index.js
  src/routes/Router.js
  src/utils/constants.js
Labels: 🚀 FEAT, 💻 FE

#67 [FEAT] 관리자 공지 상세 페이지를 퍼블리싱합니다.
  src/components/admin/home/notice/Notice.js
  src/components/admin/home/notice/NoticeItem.css
  src/components/admin/notice-detail/NoticeDetailItem.css
  src/components/admin/notice-detail/NoticeDetailItem.js
  src/components/common/notice/AdminNoticeItem.js
  src/pages/admin/notice/notice-detail/NoticeDetail.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#68 [feat] 공지 관리 업로드 구현
  src/components/admin/notice-form/NoticeForm.css
  src/components/admin/notice-form/NoticeForm.js
  src/components/index.js
  src/components/user/profile/ProfileImage.js
  src/pages/admin/member/member-management/MemberManagement.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/admin/member/upload-member/UploadMember.css
  src/pages/admin/notice/upload-notice/UploadNotice.css
  src/pages/admin/notice/upload-notice/UploadNotice.js
  src/pages/index.js
  src/routes/Router.js
Labels: 🚀 FEAT, 💻 FE

#75 [STYLE] 반응형 스타일을 추가합니다.
  src/components/admin/home/notice/Notice.css
  src/components/admin/home/notice/NoticeHeader.css
  src/components/admin/home/user-list/UserList.css
  src/components/admin/home/user-list/UserList.js
  src/components/admin/home/user-list/UserListHeader.css
  src/components/admin/notice-management/NoticeManagementHeader.css
  src/components/admin/vacation-management/VacationHeader.css
Labels: 🌴 STYLE, 💻 FE

#76 [feat] 관리자 공지 수정
  src/components/admin/notice-detail/NoticeDetailItem.js
  src/components/admin/notice-form/NoticeForm.js
  src/components/admin/notice-management/NoticeManagementHeader.css
  src/pages/admin/notice/edit-notice/EditNotice.css
  src/pages/admin/notice/edit-notice/EditNotice.js
  src/pages/admin/notice/upload-notice/UploadNotice.js
  src/pages/index.js
  src/routes/Router.js
  src/utils/constants.js
Labels: 🚀 FEAT, 💻 FE

#82 [STYLE] 모달 스타일을 수정합니다.
  src/components/admin/notice-detail/NoticeDetailItem.js
  src/components/common/navbar/Navbar.js
  src/components/ui/modal/Modal.css
  src/components/ui/modal/admin/adminModal.css
  src/components/ui/modal/admin/adminModal.js
  src/components/ui/modal/user/userModal.css
  src/components/ui/modal/user/userModal.js
Labels: 🌴 STYLE, 💻 FE

#86 [REFACTOR] 이벤트 위임 방식 수정
  public/assets/imgs/post/notice1.png
  public/assets/imgs/post/notice10.png
  public/assets/imgs/post/notice11.png
  public/assets/imgs/post/notice12.png
  public/assets/imgs/post/notice13.png
  public/assets/imgs/post/notice14.png
  public/assets/imgs/post/notice15.png
  public/assets/imgs/post/notice16.png
  public/assets/imgs/post/notice17.png
  public/assets/imgs/post/notice18.png
  public/assets/imgs/post/notice19.png
  public/assets/imgs/post/notice2.png
  public/assets/imgs/post/notice3.png
  public/assets/imgs/post/notice4.png
  public/assets/imgs/post/notice5.png
  public/assets/imgs/post/notice6.png
  public/assets/imgs/post/notice7.png
  public/assets/imgs/post/notice8.png
  public/assets/imgs/post/notice9.png
  public/assets/imgs/profile/profile1.webp
  public/assets/imgs/profile/profile10.webp
  public/assets/imgs/profile/profile11.webp
  public/assets/imgs/profile/profile12.webp
  public/assets/imgs/profile/profile13.webp
  public/assets/imgs/profile/profile14.webp
  public/assets/imgs/profile/profile15.webp
  public/assets/imgs/profile/profile16.webp
  public/assets/imgs/profile/profile17.webp
  public/assets/imgs/profile/profile18.webp
  public/assets/imgs/profile/profile19.webp
  public/assets/imgs/profile/profile2.jpg
  public/assets/imgs/profile/profile2.webp
  public/assets/imgs/profile/profile20.webp
  public/assets/imgs/profile/profile3.webp
  public/assets/imgs/profile/profile4.webp
  public/assets/imgs/profile/profile5.webp
  public/assets/imgs/profile/profile6.webp
  public/assets/imgs/profile/profile7.webp
  public/assets/imgs/profile/profile8.webp
  public/assets/imgs/profile/profile9.webp
  server/data/company_posts.json
  server/data/users.json
  src/components/admin/notice-detail/NoticeDetailItem.js
  src/components/common/navbar/Navbar.css
  src/components/common/navbar/Navbar.js
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#91 [FEAT] 관리자 공지관리와 휴가/공가 관리 페이지에서 페이지네이션을 구현합니다.
  src/components/admin/notice-management/NoticeManagementList.css
  src/components/admin/notice-management/NoticeManagementList.js
  src/components/admin/vacation-management/VacationList.css
  src/components/admin/vacation-management/VacationList.js
  src/components/common/notice/AdminNoticeList.js
  src/components/common/pagenation/Pagenation.css
  src/pages/admin/notice/notice-management/NoticeManagement.js
Labels: 🚀 FEAT, 💻 FE

#88 [style] 직원 목록 상세보기 반응형
  server/data/absences.json
  src/pages/admin/member/member-detail/MemberDetail.css
  src/pages/admin/member/member-detail/MemberDetail.js
Labels: 🌴 STYLE, 💻 FE

#95 [SERVER] 관리자- firebase에서 공지사항 데이터 CRUD를 구현합니다.
  server/api/admin.js
  src/components/admin/notice-detail/NoticeDetailItem.js
  src/components/admin/notice-profile/AttachProfileImageEvents.js
  src/components/common/notice/AdminNoticeList.js
  src/components/ui/modal/Modal.css
  src/components/ui/modal/Modal.js
  src/components/ui/modal/admin/adminModal.js
  src/pages/admin/notice/edit-notice/EditNotice.js
  src/pages/admin/notice/upload-notice/UploadNotice.js
  src/utils/handleProfileImg.js
Labels: 🔨 REFACTOR, 🔩 SERVER

#98 [server] 관리자 firebase 연결(직원 목록, 상세보기, 직원 업로드)
  package-lock.json
  server/api/admin.js
  server/api/user.js
  src/components/user/profile/ProfileImage.js
  src/pages/admin/member/member-detail/MemberDetail.js
  src/pages/admin/member/member-management/MemberManagement.css
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/admin/member/upload-member/UploadMember.js
  src/utils/checkAttendance.js
Labels: 🚀 FEAT, 🔩 SERVER

#99 [server] 관리자 직원 삭제 및 업로드 구현
  server/api/admin.js
  src/components/admin/home/user-list/UserList.js
  src/components/admin/notice-profile/AttachProfileImageEvents.js
  src/pages/admin/member/member-detail/MemberDetail.js
  src/pages/admin/member/member-management/MemberManagement.js
  src/pages/admin/member/upload-member/UploadMember.js
  src/pages/admin/notice/upload-notice/UploadNotice.js
Labels: 🚀 FEAT, 🔩 SERVER

#97 [Feat] 사용자 내 정보 수정 페이지, 휴가/공가 관리 페이지 서버 연결
  public/assets/imgs/auth/login_page_test.png
  public/assets/imgs/profile/profile_null.jpg
  server/api/user.js
  src/components/common/header/Header.js
  src/components/common/log-in-form/LogInForm.css
  src/components/common/log-in-form/LogInForm.js
  src/components/index.js
  src/components/ui/button/Button.js
  src/components/ui/form/FormValidation.js
  src/components/ui/modal/Modal.js
  src/components/ui/modal/user/userModal.css
  src/components/ui/modal/user/userModal.js
  src/components/user/form/edit-profile-form/EditProfileForm.css
  src/components/user/form/edit-profile-form/EditProfileForm.js
  src/components/user/form/sign-up-form/SignUpForm.css
  src/components/user/form/sign-up-form/SignUpForm.js
  src/components/user/form/vacation-request-form/VacationRequestForm.js
  src/components/user/profile/ProfileImage.js
  src/components/user/vacation/vacation-header/VacationHeader.js
  src/components/user/vacation/vacation-list/VacationList.css
  src/components/user/vacation/vacation-list/VacationList.js
  src/components/user/vacation/vacation-table/VacationTable.css
  src/components/user/vacation/vacation-table/VacationTable.js
  src/pages/admin/member/member-detail/MemberDetail.js
  src/pages/log-in/LogIn.css
  src/pages/log-in/LogIn.js
  src/pages/user/edit-profile/EditProfile.js
  src/pages/user/home/Home.js
  src/pages/user/notice/notice-detail/NoticeDetail.js
  src/pages/user/notice/notice-list/NoticeList.css
  src/pages/user/notice/notice-list/NoticeList.js
  src/pages/user/vacation/vacation-management/VacationManagement.js
  src/pages/user/vacation/vacation-request/VacationRequest.js
  src/routes/Router.js
  src/utils/extractParams.js
  src/utils/responsive.js
  src/utils/validation.js
Labels: 🚀 FEAT, 🔨 REFACTOR, 💻 FE

#102 [Style] user home
  src/components/user/home/notice-gallery/NoticeGallery.css
  src/components/user/home/punch-time/PunchTime.css
  src/components/user/peer-list/PeerList.css
  src/pages/user/notice/notice-list/NoticeList.css
  src/pages/user/notice/notice-list/NoticeList.js
  src/pages/user/peer/Peer.js
Labels: 🌴 STYLE

#104 [FEAT] 관리자- 휴가/공가 관리 페이지에서 각 버튼에 대한 요청을 합니다.
  server/api/admin.js
  server/api/user.js
  src/components/admin/vacation-management/VacationHeader.js
  src/components/admin/vacation-management/VacationList.js
  src/components/ui/modal/Modal.js
  src/pages/admin/notice/upload-notice/UploadNotice.js
  src/utils/vacationStore.js
Labels: 🚀 FEAT, 💻 FE, 🔩 SERVER
